configure: use mysql status command while waiting for the server to start

diff --git a/resources/setup/configure b/resources/setup/configure
--- a/resources/setup/configure
+++ b/resources/setup/configure
@@ -7,8 +7,20 @@ if [ ! -d "${datadir}/mysql" ]; then
 fi
 
 /usr/bin/supervisord
-sleep 3
 
+# wait for mysql server to start (max 120 seconds)
+timeout=120
+while ! mysqladmin -uroot status >/dev/null 2>&1
+do
+	timeout=$(expr $timeout - 1)
+	if [ $timeout -eq 0 ]; then
+		echo "Failed to start mysql server"
+		exit 1
+	fi
+	sleep 1
+done
+
+echo "Populating mysql database..."
 cat /mysql/setup/commands.sql | mysql
 
 echo ""
