grant remote access to root from '172.17.%.%' address space

diff --git a/assets/init b/assets/init
--- a/assets/init
+++ b/assets/init
@@ -18,9 +18,28 @@ appStart () {
 	# initialize MySQL data directory
 	if [ ! -d /var/lib/mysql/mysql ]; then
 		mysql_install_db --user=mysql
-	fi
 
-	supervisorctl start mysqld
+		# start mysql server
+		supervisorctl start mysqld
+
+		# wait for mysql server to start (max 120 seconds)
+		timeout=120
+		while ! mysqladmin -uroot status >/dev/null 2>&1
+		do
+			timeout=$(expr $timeout - 1)
+			if [ $timeout -eq 0 ]; then
+				echo "Failed to start mysql server"
+				exit 1
+			fi
+			sleep 1
+		done
+
+		# grant remote access from '172.17.%.%' address space to root user
+		echo "GRANT ALL ON *.* TO 'root'@'172.17.%.%' IDENTIFIED BY '' WITH GRANT OPTION;" | mysql -uroot
+		echo "FLUSH PRIVILEGES;" | mysql -uroot
+	else
+		supervisorctl start mysqld
+	fi
 
 	tail -F /var/log/mysql/error.log
 }
