init: manually start mysqld server

diff --git a/assets/init b/assets/init
--- a/assets/init
+++ b/assets/init
@@ -11,6 +11,29 @@ echo User: root Password: $ROOT_PASSWORD
 /usr/bin/supervisord
 
 appStart () {
+	# fix permissions and ownership of /var/lib/mysql
+	chown -R mysql:mysql /var/lib/mysql
+	chmod 700 /var/lib/mysql
+
+	# initialize MySQL data directory
+	if [ ! -d /var/lib/mysql/mysql ]; then
+		mysql_install_db --user=mysql
+	fi
+
+	supervisorctl start mysqld
+
+	# wait for mysql server to start (max 120 seconds)
+	timeout=120
+	while ! mysqladmin -uroot ${DB_PASS:+-p$DB_PASS} status >/dev/null 2>&1
+	do
+		timeout=$(expr $timeout - 1)
+		if [ $timeout -eq 0 ]; then
+			echo "Failed to start mysql server"
+			exit 1
+		fi
+		sleep 1
+	done
+
 	tail -F /var/log/mysql/error.log
 }
 
